//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.IngredientsOnPizzas = new HashSet<IngredientsOnPizza>();
            this.IngredientsOnPizzas1 = new HashSet<IngredientsOnPizza>();
            this.IngredientsOnPizzas2 = new HashSet<IngredientsOnPizza>();
            this.IngredientsOnPizzas3 = new HashSet<IngredientsOnPizza>();
            this.IngredientsOnPizzas4 = new HashSet<IngredientsOnPizza>();
            this.IngredientsOnPizzas5 = new HashSet<IngredientsOnPizza>();
            this.IngredientsOnPizzas6 = new HashSet<IngredientsOnPizza>();
            this.IngredientsOnPizzas7 = new HashSet<IngredientsOnPizza>();
            this.IngredientsOnPizzas8 = new HashSet<IngredientsOnPizza>();
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public Nullable<bool> IsSelected { get; set; }

        public List<Ingredient> IngredientsCollection { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsOnPizza> IngredientsOnPizzas8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
