//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientsOnPizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngredientsOnPizza()
        {
            this.Pizzas = new HashSet<Pizza>();
        }
    
        public int ID { get; set; }
        public int Ingredient1 { get; set; }
        public Nullable<int> Ingredient2 { get; set; }
        public Nullable<int> Ingredient3 { get; set; }
        public Nullable<int> Ingredient4 { get; set; }
        public Nullable<int> Ingredient5 { get; set; }
        public Nullable<int> Ingredient6 { get; set; }
        public Nullable<int> Ingredient7 { get; set; }
        public Nullable<int> Ingredient8 { get; set; }
        public Nullable<int> Ingredient9 { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Ingredient Ingredient10 { get; set; }
        public virtual Ingredient Ingredient11 { get; set; }
        public virtual Ingredient Ingredient12 { get; set; }
        public virtual Ingredient Ingredient13 { get; set; }
        public virtual Ingredient Ingredient14 { get; set; }
        public virtual Ingredient Ingredient15 { get; set; }
        public virtual Ingredient Ingredient16 { get; set; }
        public virtual Ingredient Ingredient17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pizza> Pizzas { get; set; }
    }
}
