//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ID { get; set; }
        public int LocationID { get; set; }
        public int Quantity { get; set; }
        public int IngredientsID { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Location Location { get; set; }
    }
}
