//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.LocationOrderLists = new HashSet<LocationOrderList>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int NumberOfPizzaOrdered { get; set; }
        public int TotalOrderPrice { get; set; }
        public int LocationID { get; set; }
        public System.DateTime OrderDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationOrderList> LocationOrderLists { get; set; }
        public virtual Location Location { get; set; }
        public virtual NumberOfPizzaOrdered NumberOfPizzaOrdered1 { get; set; }
        public virtual User User { get; set; }
    }
}
