//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pizza()
        {
            this.NumberOfPizzaOrdereds = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds1 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds2 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds3 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds4 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds5 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds6 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds7 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds8 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds9 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds10 = new HashSet<NumberOfPizzaOrdered>();
            this.NumberOfPizzaOrdereds11 = new HashSet<NumberOfPizzaOrdered>();
        }
    
        public int ID { get; set; }
        public int LocationID { get; set; }
        public int UserID { get; set; }
        public int SizeID { get; set; }
        public int CrustID { get; set; }
        public int SauceID { get; set; }
        public int IngredientsOnPizzaID { get; set; }
        public int PizzaPrice { get; set; }
    
        public virtual Crust Crust { get; set; }
        public virtual IngredientsOnPizza IngredientsOnPizza { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberOfPizzaOrdered> NumberOfPizzaOrdereds11 { get; set; }
        public virtual Sauce Sauce { get; set; }
        public virtual Size Size { get; set; }
        public virtual User User { get; set; }
    }
}
