//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaEntities : DbContext
    {
        public PizzaEntities()
            : base("name=PizzaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Crust> Crusts { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IngredientsOnPizza> IngredientsOnPizzas { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<LocationOrderList> LocationOrderLists { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationUserList> LocationUserLists { get; set; }
        public virtual DbSet<NumberOfPizzaOrdered> NumberOfPizzaOrdereds { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Pizza> Pizzas { get; set; }
        public virtual DbSet<Sauce> Sauces { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }

        public System.Data.Entity.DbSet<PizzaStore.Models.SelectIngredientsEditorViewModel> SelectIngredientsEditorViewModels { get; set; }
    }
}
